apiVersion: v2
name: oci-metrics-exporter
description: A Helm chart for aggregating and exporting OCI metrics using Telegraf.
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - prometheus
  - oci
  - metrics
  - exporter
  - telegraf
home: https://github.com/oracle/oci-hpc-oke
sources:
  - https://github.com/oracle/oci-hpc-oke
maintainers:
  - name: Andrei Ilas
    email: andrei.ilas@oracle.com