version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: gomod
    directory: /test
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: monthly
    labels:
      - dependencies
