apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: bm-gpu-l40s-nc-4
  namespace: nvidia-network-operator
spec:
  deviceType: netdevice
  mtu: 4220
  nicSelector:
    rootDevices:
    - 0000:27:00.0
    - 0000:97:00.0
    vendor: "15b3"
  nodeSelector:
    node.kubernetes.io/instance-type: "BM.GPU.L40S-NC.4"
  isRdma: true
  numVfs: 1
  priority: 90
  resourceName: sriov-rdma-vf

