{
 "title": "Block Volumes",
 "description": "Block Volumes\n",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "hostname", "query": "label_values(up, hostname)" },
   { "name": "oci_name", "query": "label_values(up, oci_name)" }
  ]
 },
 "panels": [
  {
   "title": "Read Ops Top 10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, oci_blockstore:volume_read_ops_count)",
     "legendFormat": "{{display_name}}:{{hostname}}:{{size}}"
    }
   ]
  },
  {
   "title": "Write Ops Top 10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, oci_blockstore:volume_write_ops_count)",
     "legendFormat": "{{display_name}}:{{hostname}}:{{size}}"
    }
   ]
  },
  {
   "title": "Read Throughput Top 10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, oci_blockstore:volume_read_throughput_count)",
     "legendFormat": "{{display_name}}:{{hostname}}:{{size}}"
    }
   ]
  },
  {
   "title": "Write Throughput Top 10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, oci_blockstore:volume_write_throughput_count)",
     "legendFormat": "{{display_name}}:{{hostname}}:{{size}}"
    }
   ]
  },
  {
   "title": "Throttled I/Os Top 10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk(10, oci_blockstore:volume_throttled_ios_count)",
     "legendFormat": "{{display_name}}:{{hostname}}:{{size}}"
    }
   ]
  }
 ]
}