{
 "title": "Service Gateway",
 "description": "Service Gateway\n",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Bytes From Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "oci_service_gateway:bytes_from_service_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Bytes To Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "oci_service_gateway:bytes_to_service_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Packets From Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "oci_service_gateway:packets_from_service_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Packets To Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "oci_service_gateway:packets_to_service_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Drops From Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oci_service_gateway:sgw_drops_from_service_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Drops To Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oci_service_gateway:sgw_drops_to_service_count",
     "legendFormat": "{{drop_type}}"
    }
   ]
  }
 ]
}