{
 "title": "Fast Connect",
 "description": "Fast Connect\n",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Bits Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "oci_fastconnect:bits_received_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Bits Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "oci_fastconnect:bits_sent_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Packets Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "oci_fastconnect:packets_received_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Packets Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "oci_fastconnect:packets_sent_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Packets Discarded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oci_fastconnect:packets_discarded_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Packets Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oci_fastconnect:packets_error_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Connection State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(oci_fastconnect:connection_state_count)",
     "legendFormat": "{{display_name}}"
    }
   ]
  }
 ]
}