{
 "title": "Lustre File System",
 "description": "Lustre File System\n",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "hostname", "query": "label_values(up, hostname)" },
   { "name": "oci_name", "query": "label_values(up, oci_name)" }
  ]
 },
 "panels": [
  {
   "title": "Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(oci_lustrefilesystem:read_throughput_count)",
     "legendFormat": "{{display_name}}:{{performance_tier}}"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(oci_lustrefilesystem:write_throughput_count)",
     "legendFormat": "{{display_name}}:{{performance_tier}}"
    }
   ]
  },
  {
   "title": "Data Read Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "oci_lustrefilesystem:data_read_operations_count",
     "legendFormat": "{{display_name}}:{{performance_tier}}"
    }
   ]
  },
  {
   "title": "Data Write Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "oci_lustrefilesystem:data_write_operations_count",
     "legendFormat": "{{display_name}}:{{performance_tier}}"
    }
   ]
  },
  {
   "title": "Capacity Util - Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(oci_lustrefilesystem:file_system_capacity_count)",
     "legendFormat": "{{display_name}}:{{ad}}"
    }
   ]
  },
  {
   "title": "Capacity Util - Inode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(oci_lustrefilesystem:file_system_inode_capacity_count)",
     "legendFormat": "{{display_name}}:{{ad}}"
    }
   ]
  }
 ]
}