{
 "title": "Internet Gateway",
 "description": "Internet Gateway\n",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Bytes From Internet Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "oci_internet_gateway:bytes_from_igw_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Bytes To Internet Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "oci_internet_gateway:bytes_to_igw_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Packets From Internet Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "oci_internet_gateway:packets_from_igw_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Packets To Internet Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "oci_internet_gateway:packets_to_igw_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Packet Drops From Internet Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "oci_internet_gateway:packet_drops_from_igw_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Packet Drops To Internet Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "oci_internet_gateway:packet_drops_to_igw_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  }
 ]
}