{
 "title": "Scheduling",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Waiting Pods by Reason",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(name, reason, namespace) (topk(5, label_replace(sum by(namespace, reason, pod) (max_over_time(kube_pod_container_status_waiting_reason[$__interval])) > 0, \"name\", \"$1\", \"pod\", \"(.*)-[a-z0-9]*$\")))",
     "legendFormat": "{{namespace}}/{{name}} {{reason}}"
    }
   ]
  },
  {
   "title": "Terminated Pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(namespace, reason) (max_over_time(kube_pod_container_status_terminated_reason[$__interval])) > 0",
     "legendFormat": "{{reason}}: {{namespace}}"
    }
   ]
  },
  {
   "title": "Terminated Pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(namespace, reason, pod) (max_over_time(kube_pod_container_status_terminated_reason[$__interval])) > 0",
     "legendFormat": "{{reason}}: {{namespace}} {{pod}}"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "max(sum by(instance) (kube_node_status_allocatable{resource=\"nvidia_com_gpu\"}))",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum by(namespace) (kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "Request {{namespace}}"
    },
    { "expression": "$Allocatable - $Requests", "type": "math" }
   ]
  },
  {
   "title": "Pod Status Reasons by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by(namespace, reason) (max_over_time(kube_pod_status_reason[$__interval])) > 0",
     "legendFormat": "{{reason}}: {{namespace}}"
    }
   ]
  },
  {
   "title": "Nodes with GPU Scheduling Impact",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bottomk(10,(max by(node) (max_over_time(kube_node_status_allocatable{resource=\"nvidia_com_gpu\"}[$__interval])) - sum by(node) (max_over_time(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}[$__interval]))) != 8) >= -10000",
     "legendFormat": "{{node}} {{node_prefix}}"
    }
   ]
  },
  {
   "title": "Extra Taints",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by(key) (max_over_time(kube_node_spec_taint{effect=~\"NoSchedule|NoExecute\", key!=\"nvidia.com/gpu\"}[$__interval]))",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Node Allocatable Memory by Pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(sum by(node_prefix) (label_replace(max by(node) (max_over_time(kube_node_status_allocatable{resource=\"memory\"}[$__interval])), \"node_prefix\", \"$2\", \"node\", \"(.*)-(gpu|cpu)-.*\")) > 0) - (sum by(node_prefix) (label_replace(sum by(node) (max_over_time(kube_pod_container_resource_requests{resource=\"memory\"}[$__interval])), \"node_prefix\", \"$2\", \"node\", \"(.*)-(gpu|cpu)-.*\")) > 0)",
     "legendFormat": "{{node}} {{node_prefix}}"
    }
   ]
  },
  {
   "title": "Unavailable DaemonSet Pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "max by(daemonset) (max_over_time(kube_daemonset_status_number_unavailable[$__interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Allocatable CPU Cores by Pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum by(node_prefix) (label_replace(max by(node) (max_over_time(kube_node_status_allocatable{resource=\"cpu\"}[$__interval])), \"node_prefix\", \"$2\", \"node\", \"(.*)-(gpu|cpu)-.*\")) > 0) - (sum by(node_prefix) (label_replace(sum by(node) (max_over_time(kube_pod_container_resource_requests{resource=\"cpu\"}[$__interval])), \"node_prefix\", \"$2\", \"node\", \"(.*)-(gpu|cpu)-.*\")) > 0)",
     "legendFormat": "{{node_prefix}}"
    }
   ]
  },
  {
   "title": "Node Software Versions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "sum by(kubeproxy_version) (max by(node, kubeproxy_version) (max_over_time(kube_node_info[$__interval])))",
     "legendFormat": "kube-proxy {{kubeproxy_version}}"
    },
    {
     "expr": "sum by(kubelet_version) (max by(node, kubelet_version) (max_over_time(kube_node_info[$__interval])))",
     "legendFormat": "kubelet {{kubelet_version}}"
    },
    {
     "expr": "sum by(container_runtime_version) (max by(node, container_runtime_version) (max_over_time(kube_node_info[$__interval])))",
     "legendFormat": "{{container_runtime_version}}"
    },
    {
     "expr": "sum by(kernel_version) (max by(node, kernel_version) (max_over_time(kube_node_info[$__interval])))",
     "legendFormat": "linux {{kernel_version}}"
    }
   ]
  },
  {
   "title": "Node Lowest Allocatable Ephemeral Storage by Pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(min by(node_prefix) (label_replace(min by(node) (max_over_time(kube_node_status_allocatable{resource=\"ephemeral_storage\"}[$__interval])), \"node_prefix\", \"$2\", \"node\", \"(.*)-(gpu|cpu)-.*\")) > 0) - (min by(node_prefix) (label_replace(min by(node) (max_over_time(kube_pod_container_resource_requests{resource=\"ephemeral_storage\"}[$__interval])), \"node_prefix\", \"$2\", \"node\", \"(.*)-(gpu|cpu)-.*\")) > 0)",
     "legendFormat": "{{node_prefix}}"
    }
   ]
  },
  {
   "title": "Node Error Conditions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "sum(max by(node) (max_over_time(kube_node_status_condition{condition=\"Ready\", status=\"false\"}[$__interval])) > 0)",
     "legendFormat": "NotReady"
    },
    {
     "expr": "sum(max by(node) (max_over_time(kube_node_status_condition{condition=\"MemoryPressure\", status=\"true\"}[$__interval]))) > 0",
     "legendFormat": "MemoryPressure"
    },
    {
     "expr": "sum(max by(node) (max_over_time(kube_node_status_condition{condition=\"DiskPressure\", status=\"true\"}[$__interval]))) > 0",
     "legendFormat": "DiskPressure"
    },
    {
     "expr": "sum(max by(node) (max_over_time(kube_node_status_condition{condition=\"PIDPressure\", status=\"true\"}[$__interval]))) > 0",
     "legendFormat": "PIDPressure"
    }
   ]
  }
 ]
}