apiVersion: 1
deleteRules:
    - orgId: 1
      uid: oke_npd_dcgm_health
    - orgId: 1
      uid: oke_npd_gpu_fabric_mgr
    - orgId: 1
      uid: oke_npd_gpu_imex
    - orgId: 1
      uid: oke_npd_gpu_row_remap
    - orgId: 1
      uid: oke_npd_gpu_xid
    - orgId: 1
      uid: oke_npd_nvlink_speed
    - orgId: 1
      uid: oke_npd_rdma_vf_counters
    - orgId: 1
      uid: oke_npd_rdma_vf_routes
