apiVersion: 1
groups:
    - orgId: 1
      name: Node Problem Detector
      folder: Alerts
      interval: 1m
      rules:
        - uid: oke_npd_check_stale
          title: NPD Check Stale
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: prometheus
              model:
                editorMode: code
                expr: >-
                  (
                    max by(hostname, check) (
                      (time() - oke_npd_check_last_run_timestamp_seconds{check=~"ecc-err|bus-stat|gpu-count|gpu-pcie|bad-page|rocminfo-check|rdmalink-stat|rdmalink-flap|wpa-auth|rttcc-stat|ip-address|oca-ver|cpu-profile"})
                      > bool (2 * oke_npd_check_expected_interval_seconds{check=~"ecc-err|bus-stat|gpu-count|gpu-pcie|bad-page|rocminfo-check|rdmalink-stat|rdmalink-flap|wpa-auth|rttcc-stat|ip-address|oca-ver|cpu-profile"} + 60)
                    )
                    and on(hostname)
                    label_replace(
                      max by(node) (
                        kube_node_status_capacity{resource="amd_com_gpu"} > 0
                      ),
                      "hostname", "$1", "node", "(.*)"
                    )
                  )
                  or
                  (
                    max by(hostname, check) (
                      (time() - oke_npd_check_last_run_timestamp_seconds{check=~"ecc-err|rowremap-err|bus-stat|gpu-count|gpu-pcie|fabric-mgr|xid-err|rdmalink-stat|rdmalink-flap|wpa-auth|rttcc-stat|ip-address|oca-ver|cpu-profile|nvlink-speed|dcgmi-health|rdma-vf-routes|rdma-vf-counters|imex"})
                      > bool (2 * oke_npd_check_expected_interval_seconds{check=~"ecc-err|rowremap-err|bus-stat|gpu-count|gpu-pcie|fabric-mgr|xid-err|rdmalink-stat|rdmalink-flap|wpa-auth|rttcc-stat|ip-address|oca-ver|cpu-profile|nvlink-speed|dcgmi-health|rdma-vf-routes|rdma-vf-counters|imex"} + 60)
                    )
                    and on(hostname)
                    label_replace(
                      max by(node) (
                        kube_node_status_capacity{resource="nvidia_com_gpu"} > 0
                      ),
                      "hostname", "$1", "node", "(.*)"
                    )
                  )
                  or
                  max by(hostname, check) (
                    (
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource=~"(amd|nvidia)_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "ecc-err", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource=~"(amd|nvidia)_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "bus-stat", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource=~"(amd|nvidia)_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "gpu-count", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource=~"(amd|nvidia)_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "gpu-pcie", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource=~"(amd|nvidia)_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "rdmalink-stat", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource=~"(amd|nvidia)_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "rdmalink-flap", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource=~"(amd|nvidia)_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "wpa-auth", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource=~"(amd|nvidia)_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "rttcc-stat", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource=~"(amd|nvidia)_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "ip-address", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource=~"(amd|nvidia)_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "oca-ver", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource=~"(amd|nvidia)_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "cpu-profile", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource="amd_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "bad-page", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource="amd_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "rocminfo-check", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource="nvidia_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "rowremap-err", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource="nvidia_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "fabric-mgr", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource="nvidia_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "xid-err", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource="nvidia_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "nvlink-speed", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource="nvidia_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "dcgmi-health", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource="nvidia_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "rdma-vf-routes", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource="nvidia_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "rdma-vf-counters", "hostname", ".*"
                      )
                      or
                      label_replace(
                        label_replace(
                          max by(node) (
                            kube_node_status_capacity{resource="nvidia_com_gpu"} > 0
                          ) * 0 + 1,
                          "hostname", "$1", "node", "(.*)"
                        ),
                        "check", "imex", "hostname", ".*"
                      )
                    )
                    unless on(hostname, check)
                    max by(hostname, check) (
                      oke_npd_check_last_run_timestamp_seconds
                    )
                  )
                instant: true
                intervalMs: 300000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          keep_firing_for: 30m
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: ons-webhook
            repeat_interval: 24h
