apiVersion: 1
groups:
    - orgId: 1
      name: Node Problem Detector
      folder: Alerts
      interval: 1m
      rules:
        - uid: oke_npd_check_stale
          title: NPD Check Stale
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: prometheus
              model:
                editorMode: code
                expr: max by(hostname, check) ((time() - oke_npd_check_last_run_timestamp_seconds) > bool (2 * oke_npd_check_expected_interval_seconds + 60)) or ((label_replace(max by(node) (kube_node_status_capacity{resource=~"(amd|nvidia)_com_gpu"} > 0), "hostname", "$1", "node", "(.*)") * 0 + 1) unless on(hostname) max by(hostname) (oke_npd_check_last_run_timestamp_seconds))
                instant: true
                intervalMs: 300000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          keep_firing_for: 30m
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: ons-webhook
            repeat_interval: 24h
