apiVersion: 1
groups:
    - orgId: 1
      name: Node Problem Detector
      folder: OKE
      interval: 1m
      rules:
        - uid: oke_npd_rdma_link
          title: RDMA Link
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: prometheus
              model:
                editorMode: code
                expr: problem_gauge{reason="RdmaLinkHasIssues",type="RdmaLink"}
                instant: true
                intervalMs: 300000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations: {}
          labels: {}
          isPaused: false
