{
 "title": "GPU Metrics",
 "description": "GPU Metrics Dashboard for a single cluster node.\n",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "instance_shape",
    "label": "Instance Shape",
    "query": {
     "query": "label_values(node_uname_info,instance_shape)"
    }
   },
   {
    "name": "hostname",
    "label": "Node",
    "query": {
     "query": "label_values(up{instance_shape=~\"$instance_shape\"},hostname)"
    }
   },
   {
    "name": "oci_name",
    "label": "Display Name",
    "query": "label_values(up{instance_shape=~\"$instance_shape\"}, oci_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Avail GPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (hostname) (sum by (hostname, gpu_id) (amd_gpu_health == 1)) or label_replace(count by (Hostname) (sum by (Hostname, gpu) (DCGM_EXP_GPU_HEALTH_STATUS == 0)), \"hostname\", \"$1\", \"Hostname\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max GPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(max by (hostname) (amd_gpu_junction_temperature{hostname=~\"$hostname\", instance_shape=~\"$instance_shape\"})) or label_replace(ceil(max by (Hostname) (DCGM_FI_DEV_GPU_TEMP{Hostname=~\"$hostname\", oci_name=~\"$oci_name\", instance_shape=~\"$instance_shape\"})), \"hostname\", \"$1\", \"Hostname\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Memory Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(max by (hostname) (amd_gpu_memory_temperature{hostname=~\"$hostname\", instance_shape=~\"$instance_shape\"})) or label_replace(ceil(max by (Hostname) (DCGM_FI_DEV_MEMORY_TEMP{Hostname=~\"$hostname\", oci_name=~\"$oci_name\", instance_shape=~\"$instance_shape\"})), \"hostname\", \"$1\", \"Hostname\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg GPU Util by Node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (hostname) (amd_gpu_gfx_activity{hostname=~\"$hostname\", instance_shape=~\"$instance_shape\"}) or label_replace(avg by (Hostname) (DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\", oci_name=~\"$oci_name\", instance_shape=~\"$instance_shape\"}), \"hostname\", \"$1\", \"Hostname\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amd_gpu_health{hostname=~\"$hostname\", instance_shape=~\"$instance_shape\"} or label_replace(label_replace(DCGM_EXP_GPU_HEALTH_STATUS{Hostname=~\"$hostname\", oci_name=~\"$oci_name\", instance_shape=~\"$instance_shape\"} == bool 0, \"hostname\", \"$1\", \"Hostname\", \"(.*)\"), \"gpu_id\", \"$1\", \"gpu\", \"(.*)\")"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "amd_gpu_junction_temperature{hostname=~\"$hostname\", instance_shape=~\"$instance_shape\"} or label_replace(label_replace(DCGM_FI_DEV_GPU_TEMP{Hostname=~\"$hostname\", oci_name=~\"$oci_name\", instance_shape=~\"$instance_shape\"}, \"hostname\", \"$1\", \"Hostname\", \"(.*)\"), \"gpu_id\", \"$1\", \"gpu\", \"(.*)\")",
     "legendFormat": "{{ gpu_id }}"
    }
   ]
  },
  {
   "title": "GPU Powerdraw",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watts" } },
   "targets": [
    {
     "expr": "amd_gpu_package_power{hostname=~\"$hostname\", instance_shape=~\"$instance_shape\"} or label_replace(label_replace(DCGM_FI_DEV_POWER_USAGE{Hostname=~\"$hostname\", oci_name=~\"$oci_name\", instance_shape=~\"$instance_shape\"}, \"hostname\", \"$1\", \"Hostname\", \"(.*)\"), \"gpu_id\", \"$1\", \"gpu\", \"(.*)\")",
     "legendFormat": "{{ gpu_id }}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "amd_gpu_gfx_activity{hostname=~\"$hostname\", instance_shape=~\"$instance_shape\"} or label_replace(label_replace(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\", oci_name=~\"$oci_name\", instance_shape=~\"$instance_shape\"}, \"hostname\", \"$1\", \"Hostname\", \"(.*)\"), \"gpu_id\", \"$1\", \"gpu\", \"(.*)\")",
     "legendFormat": "{{ gpu_id }}"
    }
   ]
  },
  {
   "title": "GPU Memory Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "amd_gpu_memory_temperature{hostname=~\"$hostname\", instance_shape=~\"$instance_shape\"} or label_replace(label_replace(DCGM_FI_DEV_MEMORY_TEMP{Hostname=~\"$hostname\", oci_name=~\"$oci_name\", instance_shape=~\"$instance_shape\"}, \"hostname\", \"$1\", \"Hostname\", \"(.*)\"), \"gpu_id\", \"$1\", \"gpu\", \"(.*)\")",
     "legendFormat": "{{ gpu_id }}"
    }
   ]
  },
  {
   "title": "GPU Clock (System)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "max by (hostname, gpu_id) (amd_gpu_clock{clock_type=\"system\", hostname=~\"$hostname\", instance_shape=~\"$instance_shape\"}) or label_replace(label_replace(DCGM_FI_DEV_SM_CLOCK{Hostname=~\"$hostname\", oci_name=~\"$oci_name\", instance_shape=~\"$instance_shape\"}, \"hostname\", \"$1\", \"Hostname\", \"(.*)\"), \"gpu_id\", \"$1\", \"gpu\", \"(.*)\")",
     "legendFormat": "{{ gpu_id }}"
    }
   ]
  },
  {
   "title": "GPU Memory Controller Activity (UMC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "amd_gpu_umc_activity{hostname=~\"$hostname\", instance_shape=~\"$instance_shape\"} or label_replace(label_replace(DCGM_FI_DEV_MEM_COPY_UTIL{Hostname=~\"$hostname\", oci_name=~\"$oci_name\", instance_shape=~\"$instance_shape\"}, \"hostname\", \"$1\", \"Hostname\", \"(.*)\"), \"gpu_id\", \"$1\", \"gpu\", \"(.*)\")",
     "legendFormat": "{{ gpu_id }}"
    }
   ]
  },
  {
   "title": "GPU Fabric Rx + Tx Combined B/W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (hostname, gpu_id) ((rate(amd_gpu_xgmi_link_rx{hostname=~\"$hostname\", instance_shape=~\"$instance_shape\"}[5m]) + rate(amd_gpu_xgmi_link_tx{hostname=~\"$hostname\", instance_shape=~\"$instance_shape\"}[5m])) * 1024) or label_replace(sum by (hostname, gpu) (rate(DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL{hostname=~\"$hostname\", oci_name=~\"$oci_name\", instance_shape=~\"$instance_shape\"}[5m])) * 1024, \"gpu_id\", \"$1\", \"gpu\", \"(.*)\")",
     "legendFormat": "{{ gpu_id }}"
    }
   ]
  },
  {
   "title": "ROCEv2 Rx + Tx Combined B/W",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(\nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.H100.8\", device=~\"mlx5_0|mlx5_1|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_12|mlx5_13|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.H200.8\", device=~\"mlx5_0|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_9|mlx5_10|mlx5_11\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.B4.8\", device=~\"mlx5_1|mlx5_2|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_11|mlx5_12|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.A100-v2.8\", device=~\"mlx5_1|mlx5_2|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_11|mlx5_12|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU4.8\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_11|mlx5_12|mlx5_13|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.MI300X.8\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.B200.8\", device=~\"mlx5_0|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_9|mlx5_10|mlx5_11\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.GB200.4\", device=~\"mlx5_0|mlx5_1|mlx5_3|mlx5_4\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.GB200-v2.4\", device=~\"mlx5_0|mlx5_1|mlx5_3|mlx5_4\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.GB200-v3.4\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_5|mlx5_6|mlx5_7|mlx5_8\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.GB300.4\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_5|mlx5_6|mlx5_7|mlx5_8\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.MI355X-v1.8\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7\"}[1m]))\nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.MI355X.8\", device=~\"mlx5_0|mlx5_1\"}[1m]))\nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.B300.8\", device=~\"mlx5_0|mlx5_1|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_12|mlx5_13|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m]))\n)\n+\n(\nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.H100.8\", device=~\"mlx5_0|mlx5_1|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_12|mlx5_13|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.H200.8\", device=~\"mlx5_0|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_9|mlx5_10|mlx5_11\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.B4.8\", device=~\"mlx5_1|mlx5_2|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_11|mlx5_12|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.A100-v2.8\", device=~\"mlx5_1|mlx5_2|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_11|mlx5_12|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU4.8\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_11|mlx5_12|mlx5_13|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.MI300X.8\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.B200.8\", device=~\"mlx5_0|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_9|mlx5_10|mlx5_11\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.GB200.4\", device=~\"mlx5_0|mlx5_1|mlx5_3|mlx5_4\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.GB200-v2.4\", device=~\"mlx5_0|mlx5_1|mlx5_3|mlx5_4\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.GB200-v3.4\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_5|mlx5_6|mlx5_7|mlx5_8\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.GB300.4\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_5|mlx5_6|mlx5_7|mlx5_8\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.MI355X-v1.8\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7\"}[1m]))\n\nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.MI355X.8\", device=~\"mlx5_0|mlx5_1\"}[1m]))\nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.B300.8\", device=~\"mlx5_0|mlx5_1|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_12|mlx5_13|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m]))\n)\n",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "ROCEv2 Tx B/W",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.H100.8\", device=~\"mlx5_0|mlx5_1|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_12|mlx5_13|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.H200.8\", device=~\"mlx5_0|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_9|mlx5_10|mlx5_11\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.B4.8\", device=~\"mlx5_1|mlx5_2|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_11|mlx5_12|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.A100-v2.8\", device=~\"mlx5_1|mlx5_2|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_11|mlx5_12|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU4.8\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_11|mlx5_12|mlx5_13|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.MI300X.8\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.B200.8\", device=~\"mlx5_0|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_9|mlx5_10|mlx5_11\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.GB200.4\", device=~\"mlx5_0|mlx5_1|mlx5_3|mlx5_4\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.GB200-v2.4\", device=~\"mlx5_0|mlx5_1|mlx5_3|mlx5_4\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.GB200-v3.4\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_5|mlx5_6|mlx5_7|mlx5_8\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.GB300.4\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_5|mlx5_6|mlx5_7|mlx5_8\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.MI355X-v1.8\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.MI355X.8\", device=~\"mlx5_0|mlx5_1\"}[1m]))\nor \nsum by (device) (irate(node_infiniband_port_data_transmitted_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.B300.8\", device=~\"mlx5_0|mlx5_1|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_12|mlx5_13|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m]))",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "ROCEv2 Rx B/W",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.H100.8\", device=~\"mlx5_0|mlx5_1|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_12|mlx5_13|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.H200.8\", device=~\"mlx5_0|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_9|mlx5_10|mlx5_11\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.B4.8\", device=~\"mlx5_1|mlx5_2|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_11|mlx5_12|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.A100-v2.8\", device=~\"mlx5_1|mlx5_2|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_11|mlx5_12|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU4.8\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_11|mlx5_12|mlx5_13|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.MI300X.8\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.B200.8\", device=~\"mlx5_0|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_9|mlx5_10|mlx5_11\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.GB200.4\", device=~\"mlx5_0|mlx5_1|mlx5_3|mlx5_4\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.GB200-v2.4\", device=~\"mlx5_0|mlx5_1|mlx5_3|mlx5_4\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.GB200-v3.4\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_5|mlx5_6|mlx5_7|mlx5_8\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.GB300.4\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_5|mlx5_6|mlx5_7|mlx5_8\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.MI355X-v1.8\", device=~\"mlx5_0|mlx5_1|mlx5_2|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7\"}[1m])) \nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.MI355X.8\", device=~\"mlx5_0|mlx5_1\"}[1m]))\nor \nsum by (device) (irate(node_infiniband_port_data_received_bytes_total{hostname=~\"$hostname\", instance_shape=\"BM.GPU.B300.8\", device=~\"mlx5_0|mlx5_1|mlx5_3|mlx5_4|mlx5_5|mlx5_6|mlx5_7|mlx5_8|mlx5_9|mlx5_10|mlx5_12|mlx5_13|mlx5_14|mlx5_15|mlx5_16|mlx5_17\"}[1m]))",
     "legendFormat": "{{ device }}"
    }
   ]
  }
 ]
}