{
 "title": "Cluster Level Metrics",
 "description": "Cluster Level Aggregated Metrics Dashboard\n",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "instance_shape",
    "label": "Instance Shape",
    "query": {
     "query": "label_values(node_uname_info,instance_shape)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Avg CPU Util %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])))"
    }
   ]
  },
  {
   "title": "Avg GPU Util %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(amd_gpu_gfx_activity or DCGM_FI_DEV_GPU_UTIL)"
    }
   ]
  },
  {
   "title": "Avg Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((1 - (node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)) * 100)"
    }
   ]
  },
  {
   "title": "Avg CPU Pressure %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_pressure_cpu_waiting_seconds_total[5m]) * 100)"
    }
   ]
  },
  {
   "title": "Avg Memory Pressure %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_pressure_memory_stalled_seconds_total[5m]) * 100)"
    }
   ]
  },
  {
   "title": "Avg IO Pressure %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_pressure_io_stalled_seconds_total[5m]) * 100)"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance_shape) ((1 - (node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)) * 100)",
     "legendFormat": "{{ instance_shape }}"
    }
   ]
  },
  {
   "title": "Cluster GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance_shape) (amd_gpu_gfx_activity or DCGM_FI_DEV_GPU_UTIL)",
     "legendFormat": "{{ instance_shape }}"
    }
   ]
  },
  {
   "title": "Cluster GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (instance_shape) (amd_gpu_junction_temperature or DCGM_FI_DEV_GPU_TEMP)",
     "legendFormat": "{{ instance_shape }}"
    }
   ]
  },
  {
   "title": "Cluster GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watts" } },
   "targets": [
    {
     "expr": "sum by (instance_shape) (amd_gpu_package_power or DCGM_FI_DEV_POWER_USAGE)",
     "legendFormat": "{{ instance_shape }}"
    }
   ]
  },
  {
   "title": "Network Traffic Total RX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance_shape) (rate(node_network_receive_bytes_total{device!~\"lo|docker.*|rdma.*\"}[5m]))",
     "legendFormat": "{{ instance_shape }}"
    }
   ]
  },
  {
   "title": "Network Traffic Total TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance_shape) (rate(node_network_transmit_bytes_total{device!~\"lo|docker.*|rdma.*\"}[5m]))",
     "legendFormat": "{{ instance_shape }}"
    }
   ]
  },
  {
   "title": "Disk Read Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance_shape) (irate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "{{ instance_shape }}"
    }
   ]
  },
  {
   "title": "Disk Write Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance_shape) (irate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "{{ instance_shape }}"
    }
   ]
  }
 ]
}