{
 "title": "Command Center",
 "description": "Command Center\n",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "instance_shape",
    "label": "Instance Shape",
    "query": {
     "query": "label_values(node_uname_info,instance_shape)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (nodename) (node_uname_info))"
    }
   ]
  },
  {
   "title": "CPU Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_uname_info{instance_shape!~\"(BM|VM).GPU.*\"})"
    }
   ]
  },
  {
   "title": "GPU Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_uname_info{instance_shape=~\"(BM|VM).GPU.*\"})"
    }
   ]
  },
  {
   "title": "Healthy GPU Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_health_status == 1 and on(hostname) node_uname_info{instance_shape=~\"(BM|VM).GPU.*\"})"
    }
   ]
  },
  {
   "title": "Total GPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(amd_gpu_health) or vector(0)) + (sum(max by (instance) (DCGM_FI_DEV_COUNT)) or vector(0))"
    }
   ]
  },
  {
   "title": "Healthy GPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(amd_gpu_health == 1) or vector(0)) + (sum(max by (hostname) (DCGM_FI_DEV_COUNT) * on(hostname) group_left() (node_health_status == 1)) or vector(0))"
    }
   ]
  },
  {
   "title": "Compute Node Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_health_status * on(hostname) group_left() node_uname_info{instance_shape=~\"(BM|VM).GPU.*\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Historical Cluster Node Health",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "node_health_status * on(hostname) group_left() node_uname_info{instance_shape=~\"(BM|VM).GPU.*\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Cluster Alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 } }
 ]
}