{
 "title": "GPU Health Status",
 "description": "GPU Node Component Health Status\n",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "hostname", "label": "Node", "query": { "query": "label_values(up,hostname)" } }
  ]
 },
 "panels": [
  {
   "title": "RTTCC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(hostname) (\n  problem_gauge{reason=\"RdmaRttccHasIssues\", type=\"RdmaRttcc\"} == bool 0\n  and on(hostname) up{job=\"gpu-rdma-node-problem-detector\"} == 1\n)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "OCA Ver",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(hostname) (\n  problem_gauge{reason=\"OcaVersionHasIssues\", type=\"OcaVersion\"} == bool 0\n  and on(hostname) up{job=\"gpu-rdma-node-problem-detector\"} == 1\n)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "RDMA Dev",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(hostname) (\n  problem_gauge{reason=\"RdmaLinkHasIssues\", type=\"RdmaLink\"} == bool 0\n  and on(hostname) up{job=\"gpu-rdma-node-problem-detector\"} == 1\n)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Bus Issue",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(hostname) (\n  problem_gauge{reason=\"GpuBusHasIssues\", type=\"GpuBus\"} == bool 0\n  and on(hostname) up{job=\"gpu-rdma-node-problem-detector\"} == 1\n)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Link Flap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(hostname) (\n  problem_gauge{reason=\"RdmaLinkFlappingHasIssues\", type=\"RdmaLinkFlapping\"} == bool 0\n  and on(hostname) up{job=\"gpu-rdma-node-problem-detector\"} == 1\n)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ECC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(hostname) (\n  problem_gauge{reason=\"GpuEccHasIssues\", type=\"GpuEcc\"} == bool 0\n  and on(hostname) up{job=\"gpu-rdma-node-problem-detector\"} == 1\n)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Row Remap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(hostname) (\n  problem_gauge{reason=\"GpuRowRemapHasIssues\", type=\"GpuRowRemap\"} == bool 0\n  and on(hostname) up{job=\"gpu-rdma-node-problem-detector\"} == 1\n)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Xid",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (hostname) (\n  (increase(DCGM_EXP_XID_ERRORS_COUNT[5m]) == bool 0)\n  and on(hostname)\n  up{job=\"gpu-rdma-node-problem-detector\"} == 1\n)\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Power Violation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (hostname) (\n  (increase(DCGM_FI_DEV_POWER_VIOLATION[5m]) == bool 0)\n  and on(hostname)\n  up{job=\"gpu-rdma-node-problem-detector\"} == 1\n)\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Board Limit Violation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (hostname) (\n  (increase(DCGM_FI_DEV_BOARD_LIMIT_VIOLATION[5m]) == bool 0)\n  and on(hostname)\n  up{job=\"gpu-rdma-node-problem-detector\"} == 1\n)\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Thermal Violation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (hostname) (\n  (increase(DCGM_FI_DEV_THERMAL_VIOLATION[5m]) == bool 0)\n  and on(hostname)\n  up{job=\"gpu-rdma-node-problem-detector\"} == 1\n)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Sync Boost Violation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (hostname) (\n  (increase(DCGM_FI_DEV_SYNC_BOOST_VIOLATION[5m]) == bool 0)\n  and on(hostname)\n  up{job=\"gpu-rdma-node-problem-detector\"} == 1\n)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Reliability Violation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (hostname) (\n  (increase(DCGM_FI_DEV_RELIABILITY_VIOLATION[5m]) == bool 0)\n  and on(hostname)\n  up{job=\"gpu-rdma-node-problem-detector\"} == 1\n)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "PCIE Correctable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(hostname) (\n  problem_gauge{reason=\"PcieCorrectable\", type=\"NodeHasPcieErrors\"} == bool 0\n  and on(hostname) up{job=\"gpu-rdma-node-problem-detector\"} == 1\n)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "PCIE Non Fatal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(hostname) (\n  problem_gauge{reason=\"PcieNonFatal\", type=\"NodeHasPcieErrors\"} == bool 0\n  and on(hostname) up{job=\"gpu-rdma-node-problem-detector\"} == 1\n)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "PCIE Fatal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(hostname) (\n  problem_gauge{reason=\"PcieFatal\", type=\"NodeHasPcieErrors\"} == bool 0\n  and on(hostname) up{job=\"gpu-rdma-node-problem-detector\"} == 1\n)\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "PCIE Link Width",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(hostname) (\n  problem_gauge{reason=\"GpuPcieHasIssues\", type=\"GpuPcie\"} == bool 0\n  and on(hostname) up{job=\"gpu-rdma-node-problem-detector\"} == 1\n)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Disk free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by (hostname)\n  (node_filesystem_avail_bytes{mountpoint=\"/\", device=~\"/dev/sd.*\"})\n  >= bool 50 * 1024 * 1024 * 1024)\nand on(hostname)\nup{job=\"gpu-rdma-node-problem-detector\"} == 1\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Mem free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  avg by (hostname) (\n    node_memory_MemAvailable_bytes{instance_shape=~\"(BM|VM).GPU.*\"}\n  )\n  >= bool 50 * 1024 * 1024 * 1024\n)\nand on(hostname)\nup{job=\"gpu-rdma-node-problem-detector\"} == 1\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "PCIE Health Score history",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (hostname, device) (\n    increase(problem_counter{reason=\"PcieCorrectable\", hostname=~\"$hostname\"}[5m]) * 1\n)\n+\nsum by (hostname, device) (\n    increase(problem_counter{reason=\"PcieNonFatal\", hostname=~\"$hostname\"}[5m]) * 10\n)\n+\nsum by (hostname, device) (\n    increase(problem_counter{reason=\"PcieFatal\", hostname=~\"$hostname\"}[5m]) * 100\n)\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "RDMA Link Flapping history",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "min by(hostname) (problem_gauge{reason=\"RdmaLinkFlappingHasIssues\",type=\"RdmaLinkFlapping\"} == bool 0)",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}