{
 "title": "Host Metrics",
 "description": "Host Metrics Dashboard for a single cluster node.\n",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "worker_pool_name",
    "label": "Worker Pool",
    "query": {
     "query": "label_values(up,worker_pool_name)"
    }
   },
   { "name": "hostname", "label": "Node", "query": "label_values(up, hostname)" },
   { "name": "oci_name", "label": "Display Name", "query": "label_values(up, oci_name)" },
   {
    "name": "fstype",
    "label": "File System Type",
    "query": "label_values(node_filesystem_free_bytes, fstype)"
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": "label_values(rdma_np_ecn_marked_roce_packets, interface)"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "label_values(node_network_receive_bytes_total, device)"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "label_values(node_filesystem_free_bytes, mountpoint)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Avail",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(100 * (avg by (hostname, oci_name) (irate(node_cpu_seconds_total{hostname=~\"$hostname\",oci_name=~\"$oci_name\",mode=\"idle\"}[5m]))))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory Avail",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil((node_memory_MemAvailable_bytes{hostname=~\"$hostname\",oci_name=~\"$oci_name\"}/node_memory_MemTotal_bytes{hostname=~\"$hostname\",oci_name=~\"$oci_name\"})*100)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Boot Vol Avail",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil((node_filesystem_avail_bytes{hostname=~\"$hostname\",oci_name=~\"$oci_name\",mountpoint=~\"/\"} / node_filesystem_size_bytes{hostname=~\"$hostname\",oci_name=~\"$oci_name\",mountpoint=~\"/\"})*100)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU Pressure",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(avg by (hostname, oci_name) (rate(node_pressure_cpu_waiting_seconds_total{hostname=~\"$hostname\",oci_name=~\"$oci_name\"}[5m]) * 100))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory Stalled",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(avg by (hostname, oci_name) (rate(node_pressure_memory_stalled_seconds_total{hostname=~\"$hostname\",oci_name=~\"$oci_name\"}[5m]) * 100))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "IO Stalled",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(avg by (hostname, oci_name) (rate(node_pressure_io_stalled_seconds_total{hostname=~\"$hostname\",oci_name=~\"$oci_name\"}[5m]) * 100))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ceil(avg by (mode) (rate(node_cpu_seconds_total{hostname=~\"$hostname\", mode!~\"idle\"}[5m])) * 100)",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ceil((1 - (node_memory_MemAvailable_bytes{hostname=~\"$hostname\",oci_name=~\"$oci_name\"}/node_memory_MemTotal_bytes{hostname=~\"$hostname\",oci_name=~\"$oci_name\"}))*100)",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Disk reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{hostname=~\"$hostname\",oci_name=~\"$oci_name\"}[5m])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Disk writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{hostname=~\"$hostname\",oci_name=~\"$oci_name\"}[5m])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Network Traffic Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{hostname=~\"$hostname\",oci_name=~\"$oci_name\",device=~\"$device\",device!~\"lo|docker.*|rdma.*\"}[5m])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Network Traffic Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{hostname=~\"$hostname\",oci_name=~\"$oci_name\",device=~\"$device\",device!~\"lo|docker.*|rdma.*\"}[5m])",
     "legendFormat": "{{ device }}"
    }
   ]
  }
 ]
}