{
 "title": "CoreDNS",
 "tags": [
  "network",
  "dns"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"coredns\"}, instance)"
    }
   },
   {
    "name": "zone",
    "label": "Zone",
    "query": {
     "query": "label_values(coredns_dns_requests_total{zone=~\".+\", zone!~\"monitoring.svc.cluster.local.|volcano-system.svc.cluster.local.|default.svc.cluster.local.|cluster.local.\"},zone)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests (by instance)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests (by proto)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(proto) (rate(coredns_dns_requests_total{instance=~\"$instance\", zone=~\"$zone\"}[$__rate_interval]))",
     "legendFormat": "{{proto}}"
    }
   ]
  },
  {
   "title": "Requests (by zone)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(zone) (rate(coredns_dns_requests_total{instance=~\"$instance\", zone!~\"cluster.local.|volcano-system.svc.cluster.local.|default.svc.cluster.local.|monitoring.svc.cluster.local.\"}[$__rate_interval]))",
     "legendFormat": "{{zone}}"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Success cache (size)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(zones) (coredns_cache_entries{instance=~\"$instance\", type=\"success\"})",
     "legendFormat": "{{zones}}"
    }
   ]
  },
  {
   "title": "Cache (hitrate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dnssec_cache_hits_total{instance=~\"$instance\"}[$__rate_interval])) / sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "hits: DNSSEC"
    },
    {
     "expr": "(sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[5m])) - sum(rate(coredns_dnssec_cache_hits_total{instance=~\"$instance\"}[$__rate_interval]))) / sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "misses: DNSSEC"
    },
    { "expression": "$HitSuccess / $Requests", "type": "math" },
    { "expression": "$HitDenial / $Requests", "type": "math" },
    {
     "expression": "($Requests - $HitSuccess) / $Requests",
     "type": "math"
    }
   ]
  },
  {
   "title": "Denial cache (size)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(zones) (coredns_cache_entries{instance=~\"$instance\", zones!~\"cluster.local.,in-addr.arpa.\", type=\"denial\"})",
     "legendFormat": "{{zones}}"
    }
   ]
  },
  {
   "title": "Cache requests (by zones)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(zones) (rate(coredns_cache_requests_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{zones}}"
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests ($__interval total)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(to) (increase(coredns_forward_requests_total{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "{{to}}"
    }
   ]
  },
  {
   "title": "External Responses ($__interval total)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expression": "$Total - $Hits", "type": "math" }
   ]
  },
  {
   "title": "Responses (by code)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_responses_total{instance=~\"$instance\"}[5m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Cache (hitrate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$Hits / $Requests", "type": "math" },
    { "expression": "$Misses / $Requests", "type": "math" }
   ]
  },
  {
   "title": "Responses (latency)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_forward_request_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_forward_request_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_forward_request_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Zone: $zone",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "zone",
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (by proto)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(proto) (rate(coredns_dns_requests_total{instance=~\"$instance\", zone=~\"$zone\"}[$__rate_interval]))",
       "legendFormat": "{{proto}}"
      }
     ]
    },
    {
     "title": "Requests (by type)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 6, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(type) (rate(coredns_dns_requests_total{instance=~\"$instance\", zone=~\"$zone\"}[$__rate_interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Responses (latency)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 13, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\", zone=~\"$zone\"}[$__rate_interval])))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\", zone=~\"$zone\"}[$__rate_interval])))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\", zone=~\"$zone\"}[$__rate_interval])))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Responses (by code)",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_responses_total{instance=~\"$instance\"}[5m])) by (rcode)",
       "legendFormat": "{{rcode}}"
      }
     ]
    },
    {
     "title": "Requests (size)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[$__rate_interval])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[$__rate_interval])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[$__rate_interval])) by (le))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Responses (size)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[$__rate_interval])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[$__rate_interval])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[$__rate_interval])) by (le))",
       "legendFormat": "50%"
      }
     ]
    }
   ]
  },
  {
   "title": "Health: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "repeat": "instance",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "coredns_build_info{instance=~\"$instance\"}",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Upstream Health Check Fails",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_healthcheck_broken_total{instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Upstream Rejected Queries",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_max_concurrent_rejects_total{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Panics",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(rate(coredns_panics_total{instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Failed Reloads",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(rate(coredns_reload_failed_total{instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Time",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}