{
 "title": "Node Utilization",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(5, sum by(pod) (rate(node_pressure_memory_seconds_waiting{job=\"default/vcjob-node-exporter\"}[$__rate_interval])) > 0.001)",
     "legendFormat": "{{pod}} memory waiting"
    },
    {
     "expr": "topk(5, sum by(pod) (rate(node_pressure_cpu_waiting_seconds_total{job=\"default/vcjob-node-exporter\"}[$__rate_interval])) > 0.01)",
     "legendFormat": "{{pod}} cpu waiting"
    },
    {
     "expr": "topk(5, sum by(pod) (rate(node_pressure_io_waiting_seconds_total{job=\"default/vcjob-node-exporter\"}[$__rate_interval])) > 0.0055)",
     "legendFormat": "{{pod}} io waiting"
    }
   ]
  },
  {
   "title": "Max Arp Size by Instance & Interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(sum by(device, pod) (max_over_time(node_arp_entries{device=~\"flannel.1|cni0\"}[$__interval])))",
     "legendFormat": "flannel"
    },
    {
     "expr": "max(sum by(device, pod) (max_over_time(node_arp_entries{device=~\"net.*\"}[$__interval])))",
     "legendFormat": "rdma"
    },
    {
     "expr": "max(sum by(device, pod) (max_over_time(node_arp_entries{device=~\"ens3|eth0\"}[$__interval])))",
     "legendFormat": "primary"
    }
   ]
  },
  {
   "title": "Conntrack entries/limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (last_over_time(node_nf_conntrack_entries[$__interval])) > 0",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "min(min_over_time(node_nf_conntrack_entries_limit{job=\"default/vcjob-node-exporter\"}[$__interval]))",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum by(pod) (last_over_time(node_nf_conntrack_entries{job=\"default/vcjob-node-exporter\"}[$__interval])) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Arp Entries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (sum by(pod, device) (last_over_time(node_arp_entries{job=\"default/vcjob-node-exporter\"}[$__interval])))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by(instance) (last_over_time(node_arp_entries{job=\"node-exporter\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "max(process_open_fds)", "legendFormat": "Max used" },
    { "expr": "min(process_max_fds)", "legendFormat": "Min limit" }
   ]
  }
 ]
}