apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: amd-device-metrics-exporter-oke
  namespace: kube-amd-gpu
  labels:
    release: kube-prometheus-stack
spec:
  attachMetadata:
    node: true
  selector:
    matchExpressions:
      - key: app.kubernetes.io/service
        operator: Exists
  namespaceSelector:
    matchNames:
      - kube-amd-gpu
  endpoints:
    - port: exporter-port
      path: /metrics
      interval: 30s
      honorLabels: true
      honorTimestamps: true
      relabelings:
        - action: keep
          sourceLabels:
            - __meta_kubernetes_service_label_app_kubernetes_io_service
            - __meta_kubernetes_pod_label_app_kubernetes_io_name
          separator: ";"
          regex: ".+-metrics-exporter;metrics-exporter"
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: hostname
        - action: replace
          sourceLabels:
            - __meta_kubernetes_node_label_oci_oraclecloud_com_host_serial_number
          targetLabel: host_serial_number
        - action: replace
          sourceLabels:
            - __meta_kubernetes_node_label_node_kubernetes_io_instance_type
          targetLabel: instance_shape
