apiVersion: v1
kind: Service
metadata:
  name: {{ include "oci-metrics-exporter.fullname" . }}
  labels:
    {{- include "oci-metrics-exporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.telegraf.prometheus_port }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    {{- include "oci-metrics-exporter.selectorLabels" . | nindent 4 }}
