alertmanager:
  enabled: false

defaultRules:
  create: false

prometheusSpec:
  serviceMonitorSelectorNilUsesHelmValues: false
  podMonitorSelectorNilUsesHelmValues: false
  ruleSelectorNilUsesHelmValues: false
  probeSelectorNilUsesHelmValues: false
  scrapeConfigSelectorNilUsesHelmValues: false
  remoteWriteDashboards: true
  storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: "oci-bv"
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Gi

prometheus-node-exporter:
  prometheus:
    monitor:
      relabelings:
        - sourceLabels: [__meta_kubernetes_node_label_node_kubernetes_io_instance_type]
          targetLabel: instance_shape
        - sourceLabels: [__meta_kubernetes_node_provider_id]
          targetLabel: instance_id
        - sourceLabels: [__meta_kubernetes_node_label_oci_oraclecloud_com_host_serial_number]
          targetLabel: host_serial_number         
      attachMetadata:
        node: true

grafana:
  defaultDashboardsEnabled: false
  service:
    type: LoadBalancer
  persistence:
    enabled: true
    type: sts
    storageClassName: "oci-bv"
    accessModes:
      - ReadWriteOnce
    size: 50Gi
    finalizers:
      - kubernetes.io/pvc-protection
  sidecar:
    alerts:
      enabled: true
    dashboards:
      provider:
        allowUiUpdates: true
        disableDelete: false
        folder: OKE
        
kubelet:
  serviceMonitor:
    attachMetadata:
      node: true