{
 "title": "Networking",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rx/Tx",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(interface) (rate(container_network_transmit_bytes_total[$__rate_interval]) + rate(container_network_receive_bytes_total[$__rate_interval])) > 1024",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Conntrack entries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (last_over_time(node_nf_conntrack_entries[$__interval])) > 0",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "min(min_over_time(node_nf_conntrack_entries_limit{job=\"default/vcjob-node-exporter\"}[$__interval]))",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum by(pod) (last_over_time(node_nf_conntrack_entries{job=\"default/vcjob-node-exporter\"}[$__interval])) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (sum by(instance, device) (node_network_up{device=~\"(eth0|cni0|flannel.1)\"}))",
     "legendFormat": "{{instance}} cni"
    },
    {
     "expr": "sum(last_over_time(node_network_up{device=~\"net.*|rdma.*\"}[$__interval]))",
     "legendFormat": "{{instance}} rdma"
    },
    {
     "expr": "sum (sum by(instance, device) (node_network_up{device=~\"(eth0|ens.*)\"}))",
     "legendFormat": "{{instance}} vcn"
    }
   ]
  },
  {
   "title": "Rx/Tx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(container_network_transmit_bytes_total[$__rate_interval]))",
     "legendFormat": "Tx: {{instance}}"
    },
    {
     "expr": "sum by(instance) (rate(container_network_receive_bytes_total[$__rate_interval]))",
     "legendFormat": "Rx: {{instance}}"
    }
   ]
  },
  {
   "title": "Arp Entries by Host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (sum by(instance, device) (last_over_time(node_arp_entries{}[$__interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MTU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(device) (node_network_mtu_bytes{device!=\"lo\", device!~\"veth.*\", device!~\"rdma.*\", device!=\"cni-podman0\", device!=\"eth1\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Link Down Events",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(device, instance, host_serial_number) (last_over_time(node_ethtool_link_down_events_phy[$__interval])) > 0",
     "legendFormat": "{{instance}}/{{host_serial_number}}/{{device}}"
    }
   ]
  },
  {
   "title": "TCP Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "sum by(pod) (increase(node_netstat_Tcp_OutRsts{job=\"default/vcjob-node-exporter\"}[$__interval])) > 0",
     "legendFormat": "{{pod}} OutRsts"
    },
    {
     "expr": "sum by(pod) (increase(node_netstat_Tcp_InErrs{job=\"default/vcjob-node-exporter\"}[$__interval])) > 0",
     "legendFormat": "{{pod}} InErrs"
    },
    {
     "expr": "sum by(pod) (increase(node_netstat_TcpExt_TCPTimeouts{job=\"default/vcjob-node-exporter\"}[$__interval])) > 0",
     "legendFormat": "{{pod}} Timeouts"
    },
    {
     "expr": "sum by(pod) (increase(node_netstat_TcpExt_ListenDrops{job=\"default/vcjob-node-exporter\"}[$__interval])) > 0",
     "legendFormat": "{{pod}} ListenDrops"
    }
   ]
  },
  {
   "title": "Integrity Errors",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 20 },
   "targets": [
    {
     "expr": "sum by(pod, device) (increase(node_infiniband_local_link_integrity_errors_total{job=\"default/vcjob-node-exporter\"}[$__interval])) > 0",
     "legendFormat": "{{pod}}/{{device}} link integrity"
    },
    {
     "expr": "sum by(pod, device) (increase(node_infiniband_link_downed_total{job=\"default/vcjob-node-exporter\"}[$__interval])) > 0",
     "legendFormat": "{{pod}}/{{device}} link downed"
    },
    {
     "expr": "(sum by(pod, device) (increase(node_infiniband_port_constraint_errors_received_total{job=\"default/vcjob-node-exporter\"}[$__interval])) > 0) + sum by(pod, device) (increase(node_infiniband_port_constraint_errors_transmitted_total{job=\"default/vcjob-node-exporter\"}[$__interval]))",
     "legendFormat": "{{pod}}/{{device}} port constraint"
    }
   ]
  },
  {
   "title": "Forwarding",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(node_netstat_Ip_Forwarding{job=\"default/vcjob-node-exporter\"}[$__interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Qdisc Backlog",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(pod, device, kind) (last_over_time(node_qdisc_backlog{job=\"default/vcjob-node-exporter\"}[$__interval])) > 0",
     "legendFormat": "{{pod}} {{device}} {{kind}}"
    }
   ]
  }
 ]
}