{
 "title": "RDMA Received/Transmitted bytes",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(node_exporter_build_info, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Aggregate RDMA received bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_infiniband_port_data_received_bytes_total{instance=~\"$node\",device=~\"mlx5_.+\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aggregate RDMA transmitted bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_infiniband_port_data_transmitted_bytes_total{instance=~\"$node\",device=~\"mlx5_.+\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RDMA received bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_infiniband_port_data_received_bytes_total{instance=~\"$node\",device=~\"mlx5_.+\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "RDMA transmitted bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_infiniband_port_data_transmitted_bytes_total{instance=~\"$node\",device=~\"mlx5_.+\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "$node", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "repeat": "node" }
 ]
}