{
 "title": "NAT Gateway",
 "description": "NAT Gateway\n",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Bytes From NAT Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "oci_nat_gateway:bytes_from_natgw_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Bytes To NAT Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "oci_nat_gateway:bytes_to_natgw_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Packets From NAT Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "oci_nat_gateway:packets_from_natgw_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Packets To NAT Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "oci_nat_gateway:packets_to_natgw_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Drops To NAT Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oci_nat_gateway:drops_to_natgw_count",
     "legendFormat": "{{drop_type}}"
    }
   ]
  }
 ]
}