{
 "title": "Dynamic Routing Gateway",
 "description": "Dynamic Routing Gateway\n",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Bytes From DRG Atchmnt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "oci_dynamic_routing_gateway:bytes_from_drg_attachment_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Bytes To DRG Atchmnt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "oci_dynamic_routing_gateway:bytes_to_drg_attachment_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Packets From DRG Atchmnt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "oci_dynamic_routing_gateway:packets_from_drg_attachment_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Packets To DRG Atchmnt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "oci_dynamic_routing_gateway:packets_to_drg_attachment_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Pkt Drops From DRG Atchmnt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oci_dynamic_routing_gateway:packet_drops_from_drg_attachment_count",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Pkt Drops To DRG Atchmnt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oci_dynamic_routing_gateway:packet_drops_to_drg_attachment_count",
     "legendFormat": "{{drop_type}}"
    }
   ]
  }
 ]
}